// <auto-generated />
using System;
using MailerAPIService.Models.DataContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MailAPIService.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230705080144_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MailerAPIService.Models.DataEntities.MailLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FailedMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MailDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("MessageRecipientId")
                        .HasColumnType("int");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MessageRecipientId")
                        .IsUnique();

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("MailerAPIService.Models.DataEntities.MailMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("MailerAPIService.Models.DataEntities.MessageRecipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MessageId")
                        .HasColumnType("int");

                    b.Property<int>("RecipientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.HasIndex("RecipientId");

                    b.ToTable("MessagesRecipients");
                });

            modelBuilder.Entity("MailerAPIService.Models.DataEntities.Recipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recipients");
                });

            modelBuilder.Entity("MailerAPIService.Models.DataEntities.MailLog", b =>
                {
                    b.HasOne("MailerAPIService.Models.DataEntities.MessageRecipient", "MailMessageRecipient")
                        .WithOne("MailLog")
                        .HasForeignKey("MailerAPIService.Models.DataEntities.MailLog", "MessageRecipientId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("MailMessageRecipient");
                });

            modelBuilder.Entity("MailerAPIService.Models.DataEntities.MessageRecipient", b =>
                {
                    b.HasOne("MailerAPIService.Models.DataEntities.MailMessage", "Message")
                        .WithMany("MessageRecipients")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("MailerAPIService.Models.DataEntities.Recipient", "MailRecipient")
                        .WithMany("MessageRecipients")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("MailRecipient");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("MailerAPIService.Models.DataEntities.MailMessage", b =>
                {
                    b.Navigation("MessageRecipients");
                });

            modelBuilder.Entity("MailerAPIService.Models.DataEntities.MessageRecipient", b =>
                {
                    b.Navigation("MailLog")
                        .IsRequired();
                });

            modelBuilder.Entity("MailerAPIService.Models.DataEntities.Recipient", b =>
                {
                    b.Navigation("MessageRecipients");
                });
#pragma warning restore 612, 618
        }
    }
}
